### ISSUE TITLE
Timeline?

### ISSUE THREAD

**Issue by Tim-W** [emmanuelbuah/asteroid-nativescript#1]
When are you planning to release 0.1? Do you need any help/PRs for the project?

**Comment by emmanuelbuah** [comment]
@Tim-W Frankly, I will pick up the pace here. Happy for any help. It might help for me to clean up what i have now and work from there with help from others. The most important piece after getting nativescript-websocket to work is integrating nativescripts observable library so the UI can respond to query changes. 

For now, I will focus on cleaning up the codebase and integrating nativescript-websocket. Once that's complete we can focus on query integration with nativescript UI.

**Comment by Tim-W** [comment]
@emmanuelbuah Sounds good. Let us know when you need help.
